name: dev

on:
  push:
    branches:
      - feature/*

jobs:
  repository:
    runs-on: ubuntu-24.04
    permissions: {}
    outputs:
      repository: ${{ steps.extract.outputs.repository }}
      tag: ${{ steps.extract.outputs.tag }}
    steps:
      -
        name: extract
        id: extract
        run: |
          repository=$(printf %s\\n "${{ github.repository }}" | cut -d'/' -f2)
          printf 'repository=%s\n' "$repository" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/_build.yml
    needs: repository
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [alpine]
    with:
      image: ${{ github.actor }}/${{ needs.repository.outputs.repository }}-${{ matrix.os }}
      os: ${{ matrix.os }}
      platforms: linux/amd64
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  minimal:
    uses: ./.github/workflows/_build.yml
    needs: repository
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [alpine]
    with:
      image: ${{ github.actor }}/${{ needs.repository.outputs.repository }}-${{ matrix.os }}-minimal
      platforms: linux/amd64
      os: ${{ matrix.os }}
      build-args: |
        INSTALL_FEATURES=sudo codecli cloudflare git
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}
