name: dev

on:
  push:
    branches:
      - feature/*

jobs:
  metadata:
    runs-on: ubuntu-24.04
    permissions: {}
    outputs:
      repository: ${{ steps.extract.outputs.repository }}
      tag: ${{ steps.extract.outputs.tag }}
    steps:
      -
        name: extract
        id: extract
        run: |
          repository=$(printf %s\\n "${{ github.repository }}" | cut -d'/' -f2)
          tag=${GITHUB_REF#refs/heads/}
          tag=${tag//\//-}
          printf 'repository=%s\n' "$repository" >> $GITHUB_OUTPUT
          printf 'tag=%s\n' "$tag" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/_build.yml
    needs: metadata
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [alpine]
    with:
      image: ${{ github.actor }}/${{ needs.metadata.outputs.repository }}-${{ matrix.os }}
      platforms: linux/amd64
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
